apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_fdd83d4a9779
          env:
            - name: TZ
              value: Asia/Seoul
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            requests:
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /api/test
              port: 8080
          volumeMounts:
            - name: application-yml-volume
              mountPath: /backend/application.yml
              subPath: application.yml
              readOnly: true
      volumes:
        - name: application-yml-volume
          secret:
            secretName: application-yml-secret
